INSERT INTO terms (french, japanese, category, notes) VALUES
  -- ingredient
  ('beurre',        'バター',                   'ingredient', NULL),
  ('crème fraîche', 'クレーム・フレッシュ',     'ingredient', '乳脂肪分30%以上の発酵クリーム'),
  ('farine',        '小麦粉',                   'ingredient', NULL),
  ('sel',           '塩',                       'ingredient', NULL),
  ('poivre',        'コショウ',                 'ingredient', NULL),
  ('ail',           'ニンニク',                 'ingredient', NULL),
  ('échalote',      'エシャロット',             'ingredient', NULL),
  ('thym',          'タイム',                   'ingredient', 'ハーブ'),
  ('laurier',       'ローリエ',                 'ingredient', 'ベイリーフ'),
  ('persil',        'パセリ',                   'ingredient', NULL),
  ('champignon',    'キノコ',                   'ingredient', NULL),
  ('truffe',        'トリュフ',                 'ingredient', NULL),
  ('foie gras',     'フォアグラ',               'ingredient', NULL),
  ('escargot',      'エスカルゴ',               'ingredient', 'カタツムリ'),
  -- technique
  ('sauté',         'ソテー',                   'technique',  '少量の油で炒める'),
  ('braisé',        'ブレゼ',                   'technique',  '蒸し煮'),
  ('poché',         'ポッシェ',                 'technique',  'ゆでる・湯煎'),
  ('grillé',        'グリエ',                   'technique',  '焼く・グリル'),
  ('rôti',          'ロティ',                   'technique',  'オーブンで焼く'),
  ('flambé',        'フランベ',                 'technique',  'アルコールで炎を上げる'),
  ('julienne',      'ジュリエンヌ',             'technique',  '千切り'),
  ('brunoise',      'ブリュノワーズ',           'technique',  '細かいサイコロ切り'),
  ('chiffonade',    'シフォナード',             'technique',  '葉物の細切り'),
  ('déglacer',      'デグラッセ',               'technique',  '鍋底をワインで溶かす'),
  -- dish
  ('soupe à l''oignon', 'オニオングラタンスープ', 'dish',     NULL),
  ('crêpe',             'クレープ',              'dish',      NULL),
  ('ratatouille',       'ラタトゥイユ',          'dish',      'プロヴァンスの野菜煮込み'),
  ('pot-au-feu',        'ポ・ト・フー',          'dish',      '牛肉と野菜の煮込み'),
  ('cassoulet',         'カスレ',                'dish',      '豆と肉の煮込み'),
  ('coq au vin',        'コック・オー・ヴァン',  'dish',      '鶏のワイン煮込み'),
  ('tarte tatin',       'タルト・タタン',         'dish',      'リンゴの逆さタルト'),
  ('crème brûlée',      'クレームブリュレ',       'dish',      NULL),
  ('quiche',            'キッシュ',               'dish',      NULL),
  -- utensil
  ('cocotte',    'ココット',     'utensil', '鋳物鍋'),
  ('mandoline',  'マンドリン',   'utensil', 'スライサー'),
  ('tamis',      'タミ',         'utensil', '裏ごし器'),
  ('fouet',      'フュエ',       'utensil', '泡立て器'),
  ('spatule',    'スパチュラ',   'utensil', 'へら');
